version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    # Добавляем паузу для запуска БД, добавляем применение миграций
    command: /bin/bash -c "sleep 10 && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: celery
    command: -A app.celery.celery_app worker --loglevel=info
    env_file: .env
    links:
      - redis
    depends_on:
      - redis
      - db
      - fastapi

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: celery
    command: -A app.celery.celery_app beat --loglevel=info
    env_file: .env
    links:
      - redis
    depends_on:
      - redis
      - db
      - fastapi

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "sleep 10 && celery -A app.celery.celery_app flower --loglevel=info"
    env_file: .env
    links:
      - redis
      - worker
    depends_on:
      - redis
      - worker
      - fastapi
    ports:
      - "5555:5555"

  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    container_name: telegram_bot
    env_file: .env
    depends_on:
      - db
      - redis
      - fastapi

  db:
    image: postgres:14
    container_name: postgres_db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
