"""Убрано поле image_url из модели  Product

Revision ID: 04d52a15572d
Revises: 9595b454b277
Create Date: 2024-08-29 18:24:52.761455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d52a15572d'
down_revision: Union[str, None] = '9595b454b277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
